---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: docker-cert
  labels:
    type: local
    name: dockercert
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp-docker-pv"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: docker-cert
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "standard"
  selector:
    matchLabels:
      name: dockercert
