---
apiVersion: v1
kind: Service
metadata:
  name: docker
  labels:
    run: docker
spec:
  selector:
    name: docker
  ports:
  - protocol: TCP
    targetPort: 2376
    port: 2376
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-dind
spec:
  replicas: 1
  selector:
    matchLabels:
      name: docker
  template:
    metadata:
      labels:
        name: docker
    spec:
      volumes:
      - name: dockercert
        persistentVolumeClaim:
          claimName: docker-cert
      - name: dockervolume 
        persistentVolumeClaim:
          claimName: docker-pvc
      containers:
      - name: docker
        securityContext:
          privileged: true
        image: "docker:dind" #"moduit/dind-kubectl" #"docker:18.05.0-dind" #"mpsorg/docker:18.05-0-dind" #
        env:
        - name: DOCKER_TLS_VERIFY
          value: "true"
        - name: DOCKER_TLS_CERTDIR
          value: "/certs"
        ports:
        - containerPort: 2376 
        volumeMounts:
        - mountPath: /var/lib/docker
          name: dockervolume
        - mountPath: /certs
          name: dockercert
